apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.project_name_in_k8}}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.project_name_in_k8}}
  template:
    metadata:
      annotations:
        backstage.io/kubernetes-id: ${{values.project_name_in_k8}}
    spec:
      containers:
        - name: my-${{values.project_name_in_k8}}
          image: ${{values.docker_username}}/${{values.docker_image_name}}:1
          env: 
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"  
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 500Mi
          securityContext:
            runAsUser: 1000 # Replace with your desired user ID
            runAsGroup: 1000 # Replace with your desired group ID
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
