apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ${{values.project_name}}
namespace: ${{values.project_k8_namespace}}
bases:
  - ../../base
commonAnnotations:
  app: ${{values.project_name}}
  backstage.io/kubernetes-id: ${{values.project_name | dump}}
commonLabels:
  app: ${{values.project_name}}
  backstage.io/kubernetes-id: ${{values.project_name | dump}}
# patchesStrategicMerge:
# - configmap_patch.yaml