apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kubeos-dotnet-template
  title: "Kubeos .Net 7 Service with Docker Build"
  description: "Create a simple web api using .Net 7, which has the docker file, It also has capability of adding github pipeline to build docker image and push it to docker hub."
  tags:
    - recommended
    - dotnet
    - github
    - docker
    - kubernetes
  system: kubeos-idp
spec:
  owner: platform-engineering-team
  type: service
  dependsOn: ['component:kubeos', component:kubeos-cluster, component:kubeos-baseline]
  annotations:
    github.com/project-slug: kubeosx/kubeos-dotnet-template
    backstage.io/techdocs-ref: dir:.
  parameters:
    - title: Dotnet Solution/Project details
      required:
        - project_name
        - description
        - owner
        - system
      properties:
        project_name:
          title: Name
          type: string
          description: Name of the project
          maxLength: 50
          pattern: '^[a-z0-9]+$'
 
        description:
          title: Description
          type: string
          description: Help others understand what this web api is for.

        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

        system:
          title: System
          type: string
          description: System of the component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: System

    - title: Repository details
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

    - title: Provide Docker information
      required:
        - docker_username
        - docker_password
      properties:
        docker_username:
          title: Name
          type: string
          description: Docker user name for login and will be pushed to hub.
          ui:field: EntityNamePicker

        docker_password:
          title: Password
          type: string
          description: Passwod for Login, will be stored as secrets

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          description: ${{ parameters.description }}
          project_name: ${{ parameters.project_name }}
          otlp_url: "http://jaeger-collector.observability.svc:4317/"
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          docker_username: ${{ parameters.docker_username }}
          project_k8_namespace: dev # ket default for this template as a standard to become
          kustomize_path : ./deploy/k8s/overlays/dev # kepr default for this template as a standar to become
          project_org : kubeosx # kept default for this template
          repo_branch: main # kept default for this template
          http_port: 8080

    - id: publishmain
      name: Publish Main
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.project_name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: public
        requireCodeOwnerReviews: false
        # protectDefaultBranch: false
        # protectEnforceAdmins: false
        secrets:
          "DOCKER_USER": ${{ parameters.docker_username }}
          "DOCKER_PASSWORD" :  ${{ parameters.docker_password }}
          "AppName": ${{ parameters.project_name }}

    - id: publishdev
      name: Creating Dev Banch
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.project_name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: dev
        repoVisibility: public
        requireCodeOwnerReviews: false
        # protectDefaultBranch: false
        # protectEnforceAdmins: false
        secrets:
          "DOCKER_USER": ${{ parameters.docker_username }}
          "DOCKER_PASSWORD" :  ${{ parameters.docker_password }}
          "AppName": ${{ parameters.project_name }}

    # Fetch Cloud CLuster Repo, Which is responsible to deploying using FLux
    - id: fetch-remote
      name: Fetch Remote kustomization
      action: fetch:plain
      input:
        url: https://github.com/kubeosx/kubeos-cluster.git
        targetPath: kubeos



    # Fetch a remote repo for getting template to commit in flux repo.
    - id: fetch-remote
      name: Fetch Remote kustomization
      action: fetch:template
      input:
        url: https://github.com/kubeosx/kubeos-autopr-templates.git
        path:
        targetPath: kubeos/clusters/dev
        values:
          description: ${{ parameters.description }}
          project_name: ${{ parameters.project_name }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          docker_username: ${{ parameters.docker_username }}
          project_k8_namespace: dev # ket default for this template as a standard to become
          kustomize_path : ./deploy/k8s/overlays/dev # kepr default for this template as a standar to become
          project_org : kubeosx # kept default for this template
          repo_branch: main # kept default for this template
          http_port: 8080

          
    # update the kustomization file 
    - id: append-file
      name: Append To File Or Create New
      action: roadiehq:utils:fs:append
      input:
        path: kubeos/clusters/dev/kustomization.yaml
        content: '${{ "\n  - "+ parameters.project_name }}/'

    # PR back the change
    - id: pr-repo
      name: PR to repo
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=kubeos-cluster&owner=kubeosx
        description: This is commiting project ${{ parameters.project_name }} for deployment
        branchName: feature/Onboarding-${{ parameters.project_name }}
        targetBranchName: main
        gitCommitMessage: Add New Deployment Config
        title: PR for new app :${{ parameters.project_name }}
        sourcePath: kubeos/clusters/dev
        targetPath: clusters/dev


    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output: 
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: Deployment Repo
        url: ${{ steps.pr-repo.output.remoteUrl }}
      - title: Pull Request Number
        url: ${{ steps.pr-repo.output.pullRequestNumber }}
