apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.project_name | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{values.project_name | dump}}
    backstage.io/kubernetes-namespace: ${{values.project_k8_namespace | dump}}
    prometheus.io/alert: all
  tags:
    - dotnet
    - webapi
  links:
    - url: https://github.com/${{values.destination.owner}}/${{values.destination.repo}}
      icon: web
      title: Github
    - url: https://github.com/${{values.destination.owner}}/${{values.destination.repo}}/issues
      icon: web
      title: Github Issues
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system:  ${{values.system | dump}}
  providesApis:
    - "${{values.project_name}}-api"
  dependsOn:
  {% for item in values.uses_components %}
    - {{ item.component }}
  {% endfor %}
  consumesApis:
  {% for item in values.consumes_api %}
    - {{ item.title }}
  {% endfor %}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.project_name}}-api
  description: The ${{values.project_name}} API
  tags:
    - api
    - rest
  links:
    - url: https://github.com/${{values.destination.owner}}/${{values.destination.repo}}
      icon: web
      title: Github
    - url: https://github.com/${{values.destination.owner}}/${{values.destination.repo}}/issues
      icon: web
      title: Github Issues
    - url: https://github.com/${{values.destination.owner}}/${{values.destination.repo}}/blob/main/src/openapi.json
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system:  ${{values.system | dump}}
  definition:
    $text: ./openapi.json