# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 1
  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret
      postInitApplicationSQLRefs:
        # secretRefs:
        # - name: my-secret
        #   key: secret.sql
        configMapRefs:
        - name: db-init
          key: configmap.sql
  # Require 1Gi of space
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true