apiVersion: v1
kind: Service
metadata:
  name: ${{values.project_name}}
  namespace: ${{values.project_k8_namespace}}
  labels:
    metrics-scraper: prometheus
  annotations:
    backstage.io/kubernetes-id: ${{values.project_name | dump}}
spec:
  selector:
    app: ${{values.project_name}}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
