name: .NET

on:
  push:
    branches: [main, staging, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    if: github.ref != 'refs/heads/main'
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        id: dotnetrestore
        run: dotnet restore

      - if: steps.dotnetrestore.outputs.exit_code == 0
        name: Build
        id: dotnetbuild 
        run: dotnet build --no-restore

      - if: steps.dotnetbuild.outputs.exit_code == 0
        id: dotnettest
        name: Run Tests
        run: dotnet test --no-build --verbosity normal

  build-container:
    if: github.ref == 'refs/heads/main' 
    name: Docker Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: docker build
        run: |
          docker build ./src/${{secrets.AppName}}/ -t  ${{secrets.DOCKER_USER}}/${{secrets.AppName}}:${{ github.run_number  }}
      
      - name : docker push
        run: |
          docker push ${{secrets.DOCKER_USER}}/${{secrets.AppName}}:${{ github.run_number  }}